### ISSUE TITLE
Crash seen with startup mode as running with the XML_DB format being set to JSON. [clixon : 4.7.0] 

### ISSUE THREAD

**Issue by navaneethyv** [clicon/clixon#138]
CLIXON startup configuration. 

``` 
<CLICON_XMLDB_FORMAT>json</CLICON_XMLDB_FORMAT>
 <CLICON_CLI_LINESCROLLING>0</CLICON_CLI_LINESCROLLING>
 <CLICON_STARTUP_MODE>running</CLICON_STARTUP_MODE> <<
```

Content of running_db
```
{
  "config": {
    "system-config:time-series": {
      "metric": [
        {
          "name": "if_stats1",
          "metric-prometheus-type": "gauge",
          "description": "statistics_table",
          "filter": [
            {
              "match-attribute-name": "element_type",
              "match-attribute-value": "Table",
            }
          ]
        }
      ]
    }
  }
}
```
The crash is the following
```
#0  0x00007fffe5ef77e0 in netconf_malformed_message_xml (xret=0x0, 
    message=0x555571dcd5d0 "Top-level JSON object config is not qualified with namespace which is a MUST according to RFC 7951")
    at clixon_netconf_lib.c:1123
#1  0x00007fffe5ecdff4 in _json_parse (
    str=0x55555a35a2d0 "{\n  \"config\": {\n    \"system-config:time-series\": {\n      \"metric\": [\n        {\n          \"name\": \"if_stats1\",\n          \"metric-prometheus-type\": \"gauge\"..., yb=YB_NONE, yspec=0x555571a032d0, 
    xt=0x555571dd69b0, xerr=0x0) at clixon_json.c:1263
#2  0x00007fffe5ece508 in clixon_json_parse_file (fd=6, yb=YB_NONE, yspec=0x555571a032d0, xt=0x7fffffffdf50, xerr=0x0) at clixon_json.c:1450
#3  0x00007fffe5ef4aac in xmldb_readfile (h=0x555555792620, db=0x7fffe656945e "tmp", yb=YB_NONE, yspec=0x555571a032d0, xp=0x7fffffffdff8, 
    de=0x7fffffffe030, msdiff=0x0) at clixon_datastore_read.c:449
#4  0x00007fffe5ef507a in xmldb_get_cache (h=0x555555792620, db=0x7fffe656945e "tmp", yb=YB_NONE, nsc=0x0, xpath=0x7fffe6568067 "/", 
    xtop=0x7fffffffe100, msdiff=0x0) at clixon_datastore_read.c:651
#5  0x00007fffe5ef5849 in xmldb_get0 (h=0x555555792620, db=0x7fffe656945e "tmp", yb=YB_NONE, nsc=0x0, xpath=0x7fffe6568067 "/", copy=0, 
    xret=0x7fffffffe100, msdiff=0x0) at clixon_datastore_read.c:930
#6  0x00007fffe6561e8b in startup_common (h=0x555555792620, db=0x7fffe656945e "tmp", td=0x555571da7630, cbret=0x555571daba00)

```
    xret=0x7fffffffe100, msdiff=0x0) at clixon_datastore_read.c:930

This was working in version CLIXON 4.3

**Comment by olofhagsand** [comment]
Fixed by above patch.
This is not covered by the CI tests (most non-default config options are not), and seems to solve the above case.
Please verify.
