### ISSUE TITLE
backend start resconf failed due to path string truncated

### ISSUE THREAD

**Issue by nowaits** [clicon/clixon#192]
Hi olof,
My startup_db is as following:
```
</configuration>
 .....
   <restconf xmlns="http://clicon.org/restconf">
      <enable>true</enable>
      <fcgi-socket>/home/dev/code/net-base/dist/www/fastcgi_restconf.sock</fcgi-socket>
   </restconf>
</configuration>
```
When starting clixon_backend, clixon_restconf cann't be started properly.
I review the code, and find the `char wwwstr[64]` truncated by snprintf.
https://github.com/clicon/clixon/blob/43db8dd5c566a1eb30544ef22743d8556b18638e/apps/backend/backend_plugin_restconf.c#L114-L126

```
(gdb) bt
#0  restconf_pseudo_process_control (h=0x617010) at backend_plugin_restconf.c:126
#1  0x00000000004108b2 in backend_plugin_restconf_register (h=0x617010, yspec=0x661220) at backend_plugin_restconf.c:240
#2  0x0000000000408012 in main (argc=2, argv=0x7fffffffdfe0) at backend_main.c:826
125         snprintf(wwwstr, sizeof(wwwstr)-1, "%s/clixon_restconf", clicon_option_str(h, "CLICON_WWWDIR"));
(gdb) p wwwstr
$4 = "/home/dev/code/net-base/install/clixon-debug/www/clixon_restco\000"
```

**Comment by olofhagsand** [comment]
Fixed, please verify

**Comment by nowaits** [comment]
still error with debug mode
```
(gdb) bt
#0  restconf_pseudo_process_control (h=0x617010) at backend_plugin_restconf.c:138
#1  0x00000000004108c2 in backend_plugin_restconf_register (h=0x617010, yspec=0x661590) at backend_plugin_restconf.c:246
#2  0x0000000000407fb8 in main (argc=2, argv=0x7fffffffdfe0) at backend_main.c:825
(gdb) p i
$6 = 4
(gdb) p argv[0]
$8 = 0x66b7a0 "1"
(gdb) fr
#0  restconf_pseudo_process_control (h=0x617010) at backend_plugin_restconf.c:138
138             cprintf(cb, "%d", clicon_debug_get());
```

**Comment by olofhagsand** [comment]
Please try again
