### ISSUE TITLE
SEGV on invalid netconf get-config filter statement

### ISSUE THREAD

**Issue by olofhagsand** [clicon/clixon#245]
The following netconf message makes the backend crash (the filter is invalid - uses restconf api-path instead of xpath):
```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <get-config>
    <source><candidate/></source>
    <filter type="xpath" select="/if:interfaces/if:interface='eth1'" xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces"/>
  </get-config>
</rpc>]]>]]>
```
The stacktrace in the backend:
```
#0  0x00007ffff798dd1f in xp_relop (xc1=0x5555558bcd40, xc2=0x5555558bcc90, op=XO_EQ, xrp=0x7fffffffda58)
    at clixon_xpath_eval.c:844
#1  0x00007ffff798ea9a in xp_eval (xc=0x7fffffffdba0, xs=0x5555558bc9e0, nsc=0x5555558afdc0, localonly=0, 
    xrp=0x7fffffffdab8) at clixon_xpath_eval.c:1182
#2  0x00007ffff798e727 in xp_eval (xc=0x7fffffffdba0, xs=0x5555558bca30, nsc=0x5555558afdc0, localonly=0, 
    xrp=0x7fffffffdb28) at clixon_xpath_eval.c:1091
#3  0x00007ffff798e727 in xp_eval (xc=0x7fffffffdba0, xs=0x5555558b0890, nsc=0x5555558afdc0, localonly=0, 
    xrp=0x7fffffffdc38) at clixon_xpath_eval.c:1091
#4  0x00007ffff798a96f in xpath_vec_ctx (xcur=0x5555558af520, nsc=0x5555558afdc0, 
    xpath=0x5555558bb840 "/if:interfaces/if:interface = 'eth1'", localonly=0, xrp=0x7fffffffdc38)
    at clixon_xpath.c:599
#5  0x00007ffff798b0df in xpath_vec (xcur=0x5555558af520, nsc=0x5555558afdc0, xpformat=0x7ffff79b8031 "%s", 
    vec=0x7fffffffdd90, veclen=0x7fffffffdd98) at clixon_xpath.c:786
#6  0x00007ffff7995c23 in xmldb_get_cache (h=0x555555768260, db=0x5555558b0030 "candidate", yb=YB_MODULE, 
    nsc=0x5555558afdc0, xpath=0x5555558bbf90 "/if:interfaces/if:interface = 'eth1'", xtop=0x7fffffffdec0, 
    msdiff=0x0, xerr=0x7fffffffded0) at clixon_datastore_read.c:825
#7  0x00007ffff79963c5 in xmldb_get0 (h=0x555555768260, db=0x5555558b0030 "candidate", yb=YB_MODULE, 
    nsc=0x5555558afdc0, xpath=0x5555558bbf90 "/if:interfaces/if:interface = 'eth1'", copy=1, 
    xret=0x7fffffffdec0, msdiff=0x0, xerr=0x7fffffffded0) at clixon_datastore_read.c:1115
#8  0x000055555555dc63 in client_get_config_only (h=0x555555768260, nsc=0x5555558afdc0, yspec=0x555555771ba0, 
    db=0x5555558b0030 "candidate", xpath=0x5555558bbf90 "/if:interfaces/if:interface = 'eth1'", 
    username=0x5555558b0050 "olof", depth=-1, cbret=0x5555558afba0) at backend_client.c:430
#9  0x000055555555e18f in from_client_get_config (h=0x555555768260, xe=0x5555558afa60, cbret=0x5555558afba0, 
    arg=0x5555558a0dd0, regarg=0x0) at backend_client.c:553
#10 0x00007ffff79854b6 in rpc_callback_call (h=0x555555768260, xe=0x5555558afa60, cbret=0x5555558afba0, 
    arg=0x5555558a0dd0) at clixon_plugin.c:929
#11 0x00005555555611d3 in from_client_msg (h=0x555555768260, ce=0x5555558a0dd0, msg=0x555555819de0)
    at backend_client.c:1810
```

**Comment by olofhagsand** [comment]
Cannot reproduce, added test cases for various invalid xpaths
