### ISSUE TITLE
Issue with retrieveing data over Netconf

### ISSUE THREAD

**Issue by victor74** [clicon/clixon#40]
Hi,
I built the example that is included in the distribution to test restconf and netconf. While restconf works correctly:
```
victor@lebox:/usr/local/var/example$ curl -G http://127.0.0.1/restconf/data/interfaces
{
    "interfaces": {
      "interface": [
        {
          "name": "lo",
          "type": "ex:loopback",
          "enabled": true
        },
        { 
          "name": "test",
          "type": "ex:eth",
          "enabled": true
        }
      ]
    }
  }
```
I can not achieve the same with netconf. Using a very simple ncclient code I managed to connect to Cisco sandbox netconf server and query it. While using the same code on clixon, it times out.
```
victor@lebox:~/luigi$ ssh root@localhopython discovery.py 
urn:ietf:params:xml:ns:netconf:base:1.0
urn:ietf:params:xml:ns:netconf:capability:candidate:1:0
urn:ietf:params:xml:ns:netconf:capability:validate:1.0
urn:ietf:params:netconf:capability:xpath:1.0
urn:ietf:params:netconf:capability:notification:1.0
urn:ietf:params:netconf:capability:startup:1.0



Traceback (most recent call last):
  File "discovery.py", line 11, in <module>
    netconf_reply = m.get_config(source = 'running')
  File "/home/victor/luigi/env/lib/python3.6/site-packages/ncclient/manager.py", line 170, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/home/victor/luigi/env/lib/python3.6/site-packages/ncclient/manager.py", line 240, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/home/victor/luigi/env/lib/python3.6/site-packages/ncclient/operations/retrieve.py", line 133, in request
    return self._request(node)
  File "/home/victor/luigi/env/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 342, in _request
    raise TimeoutExpiredError('ncclient timed out while waiting for an rpc reply.')
ncclient.operations.errors.TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.
```
Out of curiosity I enabled debug, and I can see the following line in the log:
```
Sep  9 10:30:35 lebox clixon_backend[12644]: backend_notify CLICON
Sep  9 10:30:35 lebox clixon_backend[12644]: from_client retval=0
Sep  9 10:30:35 lebox clixon_backend[12644]: backend_notify CLICON
Sep  9 10:30:35 lebox clixon_netconf[15911]: clicon_rpc_msg retdata:<rpc-reply><data><interfaces><interface><name>lo</name><type>ex:loopback</type><enabled>true</enabled></interface><interface><name>test</name><type>ex:eth</type><enabled>true</enabled></interface></interfaces></data></rpc-reply>
Sep  9 10:30:35 lebox clixon_backend[12644]: event_loop: FD_ISSET: local netconf client socket
Sep  9 10:30:35 lebox clixon_backend[12644]: backend_notify CLICON
Sep  9 10:30:35 lebox clixon_backend[12644]: from_client
Sep  9 10:30:35 lebox clixon_backend[12644]: backend_notify CLICON
Sep  9 10:30:35 lebox clixon_backend[12644]: from_client retval=0
Sep  9 10:30:35 lebox clixon_backend[12644]: backend_notify CLICON
```
It suggests that response is sent (or at least generated), but my client can't see it. How can I diagnose it further?

regards
Jan

**Comment by olofhagsand** [comment]
Yes, a reply is returned. Can you see earlier if the hello message was returned as well? It seems so from lines urn:ietf:params:xml:ns:netconf:base:1.0... 

It could be end-of-message delimitation /framing? Clixon still uses "]]>]]>" as in RFC 4742, (:base:1.0) not the framing in RFC  6242 section 4.1 (:base:1.1). The client should fallback to :base.1.0 framing, but maybe it does not?
