### ISSUE TITLE
Clixon-backend lacks rfc 6242 <hello> protocol

### ISSUE THREAD

**Issue by SpiffiRacoon** [clicon/clixon#532]
Clixon-backend only listens for NETCONF 1.1 chunked messages. When trying to connect via netconf application such as ncclient the connection is never established because of the lack of proper exchange of capability's aka <hello>.

Example using ncclient to connect to clixon-backend using unix_socket:

ncclient:
```
>>> from ncclient import manager
>>> clixonTest = manager.connect_UnixSocket('/usr/local/var/run/controller.sock')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/spiffi/clixon-sommar-2024/ncclient_fork/ncclient/ncclient/manager.py", line 171, in connect_UnixSocket
    session.connect(*args, **kwargs)
  File "/home/spiffi/clixon-sommar-2024/ncclient_fork/ncclient/ncclient/transport/unixSocket.py", line 63, in connect
    self._post_connect()
  File "/home/spiffi/clixon-sommar-2024/ncclient_fork/ncclient/ncclient/transport/session.py", line 127, in _post_connect
    raise error[0]
  File "/home/spiffi/clixon-sommar-2024/ncclient_fork/ncclient/ncclient/transport/session.py", line 251, in run
    raise SessionCloseError(self._buffer.getvalue())
ncclient.transport.errors.SessionCloseError: Unexpected session close
```

clixon-backend in D3 mode:
```
Jun 17 09:26:50.399365: netconf_input_chunked_framing: 2255: Netconf error: NETCONF framing error chunk-start: expected \n but received < (state:0)
Jun 17 09:26:50.399381: clixon_msg_rcv11:600: Recv [1]: EOF
```

proper framing protocol: https://datatracker.ietf.org/doc/html/rfc6242#section-4.1

**Comment by olofhagsand** [comment]
This is the internal NETCONF protocol . The external NETCONF interface supports this.
The internal protocol was updated from a proprietary framing in 7.0
There is an outdated description here: https://clixon-docs.readthedocs.io/en/latest/netconf.html#internal-netconf
Related to https://github.com/clicon/clixon/issues/530
